name: Reusable Print Environment Variable

on:
  workflow_call:inputs:
    inputs:
      environment_name:
        type: string
        required: true
  workflow_dispatch:

jobs:
  print-env:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Print environment variable
        run: echo ${{ vars.VAR }}
