name: Reusable Print Environment Variable

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    secrets:
      VAR:
        required: true

jobs:
  my-dynamic-env-job:
    runs-on: ubuntu-latest
    environment: production
    env:
      VAR: ${{ secrets.VAR }}
    steps:
      - run: |
          echo "${{ env.VAR }}"