name: Test Environment Variables

on:
  workflow_call:
    inputs:
      message:
        description: 'Custom message to print'
        required: false
        type: string
        default: 'Hello from reusable workflow'
      environment:
        description: 'Environment to use for the job'
        required: false
        type: string
        default: 'development'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Print all available context
        run: |
          echo "GitHub Environment: ${{ github.environment }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Repository: ${{ github.repository }}"

  two:
    runs-on: ubuntu-latest
    needs: one
    environment: staging
    steps:
      - name: Print custom message
        run: |
          echo "Messagse: ${{ inputs.message }}"

      - name: Print environment variable
        run: |
          echo "Environment variable example: ${{ vars.ENV_VAR || 'No ENV_VAR set' }}"

      - name: Print all available context
        run: |
          echo "GitHub Environment: ${{ github.environment }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Repository: ${{ github.repository }}"
  three:
    runs-on: ubuntu-latest
    needs: two
    environment: production
    steps:
      - name: Print custom message
        run: |
          echo "Message: ${{ inputs.message }}"

      - name: Print environment name
        run: |
          echo "Environment: ${{ vars.ENVIRONMENT || 'development' }}"

      - name: Print environment variable
        run: |
          echo "Environment variable example: ${{ vars.ENV_VAR || 'No ENV_VAR set' }}"

      - name: Print all available context
        run: |
          echo "GitHub Environment: ${{ github.environment }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Repository: ${{ github.repository }}"
